// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR2.Data;

#nullable disable

namespace PR2.Migrations
{
    [DbContext(typeof(MyApplicationContex))]
    [Migration("20231222215650_TableUsers")]
    partial class TableUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("PR2.Data.InputData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Koef")
                        .HasColumnType("REAL");

                    b.Property<double>("Cgas")
                        .HasColumnType("REAL");

                    b.Property<double>("Diam")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("TEXT");

                    b.Property<double>("C_material")
                        .HasColumnType("REAL");

                    b.Property<double>("Layer_H")
                        .HasColumnType("REAL");

                    b.Property<double>("Consum")
                        .HasColumnType("REAL");

                    b.Property<double>("T_gas")
                        .HasColumnType("REAL");

                    b.Property<double>("T_material")
                        .HasColumnType("REAL");

                    b.Property<double>("V_gas")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("InputDatas");
                });

            modelBuilder.Entity("PR2.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
